### ISSUE TITLE
Null object checks

### ISSUE THREAD

**Issue by NthPortal** [OTBProject/OTBProject#101]
Check for null if channel doesn't actually exist (for some reason. It really should, but hey): https://github.com/OTBProject/OTBProject/blob/536f80b120c644ff4129db9294b7a606842b290e/src/main/java/com/github/otbproject/otbproject/eventlistener/IrcListener.java#L22

Check for null when joining a channel if for some reason there is an error connecting to the database: https://github.com/OTBProject/OTBProject/blob/536f80b120c644ff4129db9294b7a606842b290e/src/main/java/com/github/otbproject/otbproject/channels/Channel.java#L43

**Comment by Thelonedevil** [comment]
hmm yeah null checks do sound important, although the catch all, will catch the NPE that could get thrown, log and exit :P

**Comment by NthPortal** [comment]
Yeah. Shouldn't ever really be an issue, but I'll fix it up just in case.
