### ISSUE TITLE
I change the join message but still says the old one?

### ISSUE THREAD

**Issue by Spikechrisgaming** [OTBProject/OTBProject#175]
I go into the file and set it to my own but still says the old one?

**Comment by Spikechrisgaming** [comment]
Its also with everything. Any of the messages i change doesn't change on the real bot..

**Comment by Thelonedevil** [comment]
When you changed the message, did you move the file into the "to-load" folder and restart the bot?

**Comment by Spikechrisgaming** [comment]
Well now i'm having another problem now it won't connect..i have the right username and password..and have it set to BEAM

**Comment by Thelonedevil** [comment]
Hmmm I have just connected to Beam fine, can you get the log file from ".otbproject/logs/app.log" and put the contents into a gist/pastebin please.

**Comment by Spikechrisgaming** [comment]
Thank you. I coulden't connect cause i had some bad code in some of the files and such.
