### ISSUE TITLE
Is there/will there be way to send messages from the bot to every channel it is in?

### ISSUE THREAD

**Issue by Spikechrisgaming** [OTBProject/OTBProject#176]
Is there a way to send messages to every channel its in. If there isn't will there?

**Comment by NthPortal** [comment]
There isn't at the moment, but it shouldn't be difficult to do.

**Comment by Spikechrisgaming** [comment]
It would be a very good way for people running bots to tell them about news or if its going down for a bit and such.

**Comment by Spikechrisgaming** [comment]
Thank you. That will be a nice feature to have.
