### ISSUE TITLE
I know this might be a nooby type thing to ask but..

### ISSUE THREAD

**Issue by Spikechrisgaming** [OTBProject/OTBProject#177]
I never got how these type of open source stuff worked. Like how are you meant to be able to build upon just read its code then try to work with it or is there a better way or such?

**Comment by NthPortal** [comment]
Theoretically, our code would be well documented and easy to read, but it's not well documented (and probably won't be in the near future).
Basically, if you want, you can read the code and make changes to it (obviously a background in Java is required), and then either branch off and work on your own version, or submit the changes back to the main repository as a [pull request](../pulls). If you submit a pull request and we like the changes, we might add your changes; if not, we won't.
