### ISSUE TITLE
Bot disconnects after a while?

### ISSUE THREAD

**Issue by Spikechrisgaming** [OTBProject/OTBProject#178]
I was testing a few things then went to do other stuff and watch some streams and youtube and came back and the bot was offline. The program was running and such.

**Comment by NthPortal** [comment]
Can you link to a paste (e.g. on pastebin.com) of the log `.otbproject/logs/app.log`?

**Comment by Spikechrisgaming** [comment]
I don't think i have any logs atm. But i think beam might of been having problems as a lot of other bots on there were having problems so might be why.

**Comment by NthPortal** [comment]
Yeah, it seems to be a problem with Beam's client library.

https://github.com/MCProHosting/beam-client-java/issues/14
