### ISSUE TITLE
I don't understand how the --ul= things work...

### ISSUE THREAD

**Issue by Spikechrisgaming** [OTBProject/OTBProject#180]
I don't get how the --ul= mod/sub/etc work. i have tried to put them in a command but it just prints it..i can't find out how there meant to be done..

**Comment by Thelonedevil** [comment]
If you havent read through the new documentation yet, here is a link to the section that covers the use of flags http://otbproject.github.io/docs/docs/chat-guide.html#restrictions-on-commands-and-how-to-use-flags

**Comment by Spikechrisgaming** [comment]
I fully forgot about that chat doc, As theres two. Sorry about that.

**Comment by NthPortal** [comment]
Yeah, sorry. The new one was just added yesterday, and I still have a lot of content to add to it. The new "tutorial" one is meant to explain things a lot better. The current documentation is pretty comprehensive, but often does little more than mention that certain features exist.
